name: Run

on:
  workflow_dispatch:
  #repository_dispatch:
  schedule:
   - cron: "0 4/12 * * *" 

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run
      run: |
        pip3 install requests
        python3 SignIn.py
      env:
        LUCK_DRAW: ${{ secrets.LUCK_DRAW }}
        BARK_TOKEN: ${{ secrets.BARK_TOKEN }}
        COOKIE: ${{ secrets.COOKIE }}
        REFERER: ${{ secrets.REFERER }}
